--- 
- name: playbook for installing ansible
  hosts: all
  become: yes
  tasks:
    - name: installing apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present